name = "deeds-app-mvp"
main = "functions/_worker.js"
compatibility_date = "2025-10-24"
workers_dev = true

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "DEEDS_KV"
id = "f55e73c8a0814bc9b3eea9176548e1f5"